# Use custom format
format = "$all"

# Inserts a blank line between shell prompts
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[username]
style_user = "purple bold"
style_root = "green bold"
format = "[$user]($style) "
disabled = false
show_always = true
